import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import { Loader2 } from "lucide-react";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-[12px]`}
      >
        <Suspense fallback={<GlobalLoading />}>
          <nav>
            <Link  href={"/"} >
              <h1 className="font-[700]">홈으로 가기</h1>
            </Link>
          </nav>
          {children}
        </Suspense>
      </body>
    </html>
  );
}


// 글로벌 로딩 UI
function GlobalLoading() {
  return (
    <div className="fixed inset-0 flex items-center justify-center bg-white bg-opacity-80">
      <Loader2 className="animate-spin h-8 w-8 text-blue-600" />
    </div>
  );
}
